### ISSUE TITLE
Missing creation date

### ISSUE THREAD

**Issue by moley** [rcarz/jira-client#103]
Hi, 

I like your jira-client becasue it is very handy and easy to use. I want to get the creation date from an issue, but I think this is missing, isn't it? 
Can you lead me to the feature or add it? 

Thanks
Markus

**Comment by iNikem** [comment]
This was already fixed in https://github.com/rcarz/jira-client/issues/51. New version is not released yet.

**Comment by moley** [comment]
ok, thank you... I already retried it and it works
