### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by iNikem** [rcarz/jira-client#105]
Hello. Current version was released almost a year ago. And a lot of pull requests were merged since then. Isn't it a time to release new version?

**Comment by vaesbart** [comment]
I'd also like to know when we'll finally get the latest (and greatest) version...

**Comment by ScorcherChar** [comment]
Would be nice to get the latest features

**Comment by pejobo** [comment]
A also want to request a new release

**Comment by shevek** [comment]
+1

**Comment by mikulucky** [comment]
+1

**Comment by Madsn** [comment]
+1

**Comment by avano** [comment]
+1
could you please atleast deploy the 0.6-SNAPSHOT for the time being?

**Comment by ScottG489** [comment]
+1
I don't see any reason not to at least have a snapshot or some sort of patch version (i.e. **0.6.1**) released.

**Comment by kerrykimbrough** [comment]
+1

**Comment by kerrykimbrough** [comment]
@rcarz What exactly is preventing a new release right now? Maybe we can help clear the way.

**Comment by rcarz** [comment]
@kerrykimbrough I'm really sorry... it's mostly lack of time. I wrote this library for a project at that has long since ended so I can't really test changes easily. If everyone is happy with HEAD then I can post a release before merging any new PRs.

**Comment by ScottG489** [comment]
@rcarz I can totally understand that you want to make sure it's well tested but releasing some sort of release candidate might be a good way to get other people to vet out any problems since it'll be getting used by a wider audience.

**Comment by Alan-Chen-au** [comment]
I also need a new release.

**Comment by josinaldobarbosa** [comment]
+1

**Comment by vladimirsvicevicsrb** [comment]
+1
