### ISSUE TITLE
[Help] Create new issue

### ISSUE THREAD

**Issue by cesarcardinali** [rcarz/jira-client#106]
Hi,

I am trying to create a new issue here and I have the following problem:
For components:
> net.rcarz.jiraclient.JiraException: Field expects an Iterable value
	at net.rcarz.jiraclient.Field.toJson(Field.java:543)
	at net.rcarz.jiraclient.Issue$FluentCreate.executeCreate(Issue.java:104)
	at net.rcarz.jiraclient.Issue$FluentCreate.execute(Issue.java:59)
	at tests.UserApiTest.main(UserApiTest.java:34)

For customfield_10005:
> Caused by: net.rcarz.jiraclient.RestException: 400 Bad Request: {"errorMessages":[],"errors":{"customfield_10005":"Could not find valid 'id' or 'value' in the Parent Option object."}}

And I am doing like this:

> newIssue = jira.createIssue("BATTRIAGE", "New Work")
	                    .field(Field.SUMMARY, "Java API Test")
	                    .field(Field.DESCRIPTION, "If goes will be gone.")
	                    .field("customfield_10005", "Minor")
	                    .field("components", "SAT")
	                    .execute();

I know that "components" is an auto complete text field and "customfield_10005" is a dropdown list.
The custom field options are like:
> \<select class="select cf-select" name="customfield_10005" id="customfield_10005">
                    \<option value="">None</option>
                                    \<option value="10000">Blocker</option>
                                \<option value="10001">Critical</option>
                                \<option value="10002">Major</option>
                                \<option value="10003">Minor</option>
                                \<option value="10004">Trivial</option>
            \</select>

Could you help me with that?

**Comment by nach-o-man** [comment]
As error says
> net.rcarz.jiraclient.JiraException: Field expects an **Iterable** value

The right way to add iterable values is :
```java
.field("customfield_10005", new ArrayList() {{add("Minor");}})
.field(Field.COMPONENTS, new ArrayList() {{add("SAT");}})
```

**Comment by cesarcardinali** [comment]
Thank you so much!
This API is lots easier than JRJC. Very nice work
