### ISSUE TITLE
How to get list of issues inside a specific project

### ISSUE THREAD

**Issue by gihanmaduranga** [rcarz/jira-client#120]
Hi,

I am having a problem with get list of issues inside a specific project.My project structure something like this.

Base jira url=https://myproject.info
inside base project i have setup number of projects.like TC/CODE

so far i can connect to base project successfully and can go inside the "TC" project.In there i can get lot of attributes related to the project.But i couldn't get issues listed inside that project.(I can not see any method to obtain this)

I am new to jira client API please let me know how can i get the all issues listed in "TC" project.

BasicCredentials credentials=new BasicCredentials(userName,passWord);
JiraClient jira=new JiraClient("https://myproject.info",credentials);

Project tCProject= jira.getProject("TC");
System.out.println(tCProject.getLead().toString());
//How can i get the all issues inside the TC project.

Thanks.

**Comment by bkrmrtn** [comment]
Hey @gihanmaduranga - I managed it using the search functionality; (using your example) something akin to:

`Issue.SearchResult issueResults = jira.searchIssues("project = "+tCProject.getKey());`

**Comment by gihanmaduranga** [comment]
@bkrmrtn Thanks for your reply.

**Comment by rcarz** [comment]
Thanks @bkrmrtn !
