### ISSUE TITLE
When JIRA project URL is configured with redirect, then getProject() is giving a 404 error

### ISSUE THREAD

**Issue by asp16** [rcarz/jira-client#128]
When JIRA project URL is configured with redirect, then getProject() is giving a 404 error:

404 Not Found: {"errorMessages":["No project could be found with key 'XXX'."],"errors":{}}

**Comment by nach-o-man** [comment]
Hello, how exactly is redirect configured?

**Comment by rcarz** [comment]
Unfortunately this is likely a server configuration issue. If the server returns a 404, there's really nothing jira-client can do about it.
