### ISSUE TITLE
Is this actually being supported anymore?

### ISSUE THREAD

**Issue by mikulucky** [rcarz/jira-client#135]
I have noticed that there are a growing amount of issues, as well as pull requests. Has the repository owners stopped supporting this? Should we be moving on?

**Comment by rcarz** [comment]
Yes, to the extent that I periodically review and merge pull requests when I have time. Let me know if you'd like to help maintain the library and address issues faster.

**Comment by mikulucky** [comment]
I don't mind helping out.

**Comment by rcarz** [comment]
Help would be appreciated. I don't get time to resolve issues as often as I'd like, and I don't currently have a way of testing PRs.
