### ISSUE TITLE
net.rcarz.jiraclient.JiraException: Project 'Infrastructure Monitoring'  or issue type 'Task' missing from create metadata. Do you have enough permissions?

### ISSUE THREAD

**Issue by agastyanarumanchi** [rcarz/jira-client#137]
i get this error when i try to create an issue.i have sufficient permission.i can create projects.i am not able to figure out the issue.please helm me out.
Thanks in advance

**Comment by nach-o-man** [comment]
Can you, please, provide the code sample?
