### ISSUE TITLE
Update in Maven repo

### ISSUE THREAD

**Issue by stevenlordiam** [rcarz/jira-client#142]
The current version in Maven Dependency is 0.5 since 2014, can you update the new version in maven repo so we can use the new committed code? Or is there a new repo we can use in pom.xml instead of using the whole code base downloaded from this jira-client repo from github?

Thanks.

**Comment by rcarz** [comment]
I feel bad about this since people have been asking for quite some time. I'd like to resolve a few of the remaining open issues and do some testing before publishing a release.

**Comment by rcarz** [comment]
I'm closing this since #105 exists. Feel free to continue the discussion there.
