### ISSUE TITLE
Enhance API to allow updating of comments

### ISSUE THREAD

**Issue by magicdude4eva** [rcarz/jira-client#148]
I have the use-case where I create a daily comment for a JIRA issue and would need to update the comment if the content has to change.

I do not see an option in the API that I can update an existing comment. Would be great if you could add this function.

**Comment by rcarz** [comment]
It's implemented in 74c21b5a1f660ad479c4f73a5ed266de2b3ceb40.

```java
issue.addComment("foo").update("bar");
issue.getComments().get(0).update("baz");
```
