### ISSUE TITLE
issue.getAttachments() is empty even when the issue has attachments

### ISSUE THREAD

**Issue by francismartens318** [rcarz/jira-client#149]
lib - 0.5
JIRA - v 7.0.10

Known issue  ?

**Comment by Hiren879** [comment]
This can happen when **attachment** field is set to **hide** in field configuration settings.
Please see this [LINK](https://jira.atlassian.com/browse/JRA-27637).

**Comment by rcarz** [comment]
Unfortunately this behavior (desired or not) is beyond jira-client's control.
