### ISSUE TITLE
Transition metadata errors

### ISSUE THREAD

**Issue by Onchman** [rcarz/jira-client#160]
Hi rcarz contributors,

I began to use your client for my rest connexion with Jira.
First of all, thank you for this, it's really more easy to use. Great job guys.

Si, i tried to understand your client with the  **## Quick Start Example**.
My code is as following:
`package test;

import java.util.ArrayList;
import java.util.List;

import net.rcarz.jiraclient.BasicCredentials;
import net.rcarz.jiraclient.CustomFieldOption;
import net.rcarz.jiraclient.Field;
import net.rcarz.jiraclient.Issue;
import net.rcarz.jiraclient.JiraClient;
import net.rcarz.jiraclient.JiraException;

public class test {

    public static void main(String[] args) {

        BasicCredentials creds = new BasicCredentials("username", "password");
        JiraClient jira = new JiraClient("https://extranet.artal.fr/jira", creds);

        try {
            /* Récupérer issue TES-4 de JIRA. Une exception est retournée en cas d'erreur. */
            Issue issue = jira.getIssue("JIRA-108");

            /* Open the issue and assign it to me. */
            issue.transition().field(Field.ASSIGNEE, "braz").execute("Open");

         } catch (JiraException ex) {
             System.err.println(ex.getMessage());
 
             if (ex.getCause() != null)
                System.err.println(ex.getCause().getMessage());
        }
    }
}`

When i launch this code, I have this result:

> Transition metadata is missing from jos

Moreover, when I try exactly the same script, only changing the Jira URI and the name of my request, the transition error returned is different:

> Transition was not found in metadata

I don't really know how to resolve this. 
I hope you understood my issue! :+1: 

Best regards,
Onchman.

**Comment by rcarz** [comment]
That usually means the state name (Open, in this case) supplied in ```execute``` either doesn't exist or is not available from the current state of the issue.

**Comment by rcarz** [comment]
I'm going to close this issue but feel free to continue the discussion in #147.
