### ISSUE TITLE
How to create a issue with custom fields?

### ISSUE THREAD

**Issue by fenoloco** [rcarz/jira-client#187]
Hi, 
I'm trying to use the library on a JIRA instance with custom fields. Is this possible to create a issue with custom fields. 

If I try to do this is the error:
`
net.rcarz.jiraclient.JiraException: Field 'customfield_1234' does not exist or read-only
`

**Comment by vivganes** [comment]
Hello @fenoloco 

I am able to update custom fields in the issues. But I have not tried creating an issue from the client with a custom field's value set.

Can you please share the code snippet that you are using to create an issue?  This will help in identifying what could be wrong.

**Comment by fenoloco** [comment]
It's ok, there was a problem on the metadata, I was able to get it working.
Thanks!

**Comment by maxlpy** [comment]
Hi @fenoloco
How to create a issue with custom fields? I tried, but it returns this error:
net.rcarz.jiraclient.JiraException: Field 'customfield_1234' does not exist or read-only
