### ISSUE TITLE
Comment`s created and updated field missing hour, minute and second precision

### ISSUE THREAD

**Issue by liyc98** [rcarz/jira-client#231]
`Comment.java`
in function `private void deserialise(JSONObject json){...} `has following code fragment
```
created = Field.getDate(map.get("created"));
updated = Field.getDate(map.get("updated"));
```
then `Field.java`
   ```
public static Date getDate(Object d) {
        ...
        SimpleDateFormat df = new SimpleDateFormat(DATE_FORMAT);
        ...
    }
```
in function `getDate` DATE_FORMAT is "yyyy-MM-dd" missing hour, minute and second precision

**Comment by smsotirov** [comment]
Uh ... two years and this is still not fixed. Please fix this. There should be a time in the comment create and update date.
