### ISSUE TITLE
Field 'components' does not exist or read-only

### ISSUE THREAD

**Issue by Ants-double** [rcarz/jira-client#265]
this is my code 
``` java
.field(Field.COMPONENTS,new ArrayList() {{
						add(new JSONObject().put("name","TEST"));
					}})
``` 
this is the error 
Field 'components' does not exist or read-only

**Comment by Ants-double** [comment]
I get the answer. i slove it .
jira configure no components module to create issue

**Comment by zoujunjie1216** [comment]
hi，Can you please tell me how to configure this

**Comment by zoujunjie1216** [comment]
> I get the answer. i slove it . jira configure no components module to create issue

Can you please tell me how to configure this
