### ISSUE TITLE
Authenticate multiple Users

### ISSUE THREAD

**Issue by dehlen** [rcarz/jira-client#67]
Hello,

I am running a web application on my tomcat and I really like your library which is why i am currently using it. However my application will be used by multiple users, so I can't just hardcode the username and password inside it. On the other hand I don't want to ask the user for their credentials on the client-side since it would be very insecure to transport that information from the client to the server side.

So what is the right approach to authenticate to jira with this library with multiple Users ?
I saw, that the Jira Rest API has the possibility to submit the credentials bas64 encoded. Can I use this feature with this library ?

Thanks in advance

**Comment by chaplinkyle** [comment]
Sorry for the delay. Is this still an issue?

**Comment by rcarz** [comment]
Base64-encoding isn't anymore secure than plain text. You would need to setup SSL and collect credentials from the users. You can also setup a Kerberos or an SSO to avoid passing credentials, but you'd need to write a new authentication handler for jira-client (patches are welcome!). Alternatively, you could use a service account to access and update issues.
