### ISSUE TITLE
Page refresh ?

### ISSUE THREAD

**Issue by vaesbart** [rcarz/jira-client#69]
Ok, this may seem like a silly question (or out of scope of this project) but... I'm trying to use jira-client to update a field (like Comment) and immediately show it in the browser.
I assumed I didn't have to do manual page refresh ?

Sample code:
````java
...
   //Add comment to issue - THIS WORKS BUT NEEDS REFRESH
   issue.addComment("my comment");

   //Following line throws error : Field expects an Iterable value
   issue.update().field(Field.COMMENT, "my comment").execute();   
...
````

What do I need to get the updated fields visible in browser ?

TIA
Bart

**Comment by chaplinkyle** [comment]
This is out of scope for this project. The field does not update because that's not how JIRA currently works. I suggest submitting an issue to Atlassian for this functionality. @rcarz This issue can be closed.

**Comment by vaesbart** [comment]
Ok, thanks for the feedback.
