### ISSUE TITLE
When creating a new project, getting error

### ISSUE THREAD

**Issue by aarangara** [rcarz/jira-client#70]
Hi,

I am trying to create new project (I am not using maven, just downloaded and imported the project in eclipse), I am getting compilation error in many files :+1: 

private void deserialise(JSONObject json) {
        Map map = json;
......

This definitely is a legitimate compilation error. I am not sure how this project is evne build with this line in place.

Even the source file present in github has this line.

Please let me know if this issue is a known issue or I am missing something.

**Comment by dimapasko** [comment]
Hi @aarangara 

Why do you think this an error?

It should compiles:

```public final class JSONObject extends AbstractJSON implements JSON, Map, Comparable```

**Comment by dimapasko** [comment]
FYI
```jira-client``` use ```JSONObject ``` implementation from ```json-lib``` (http://json-lib.sourceforge.net/)

**Comment by aarangara** [comment]
Yes, I added wrong library.

But now I am facing another issue : 

RestClient.java
line 174 saying : Exception UnsupportedEncodingException  is never thrown from try body statement (I have added httpcore-4.4.jar).

            try {
                ent = new StringEntity(payload, "UTF-8");
                ent.setContentType("application/json");
            } catch (UnsupportedEncodingException ex) {
                /* utf-8 should always be supported... */
            }

**Comment by chaplinkyle** [comment]
Hope this isn't too late. Here is the full dependency tree generated by running 'mvn dependency:tree'

[INFO] net.rcarz:jira-client:jar:0.6-SNAPSHOT
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.2.5:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.2.4:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.2.5:compile
[INFO] +- net.sf.json-lib:json-lib:jar:jdk15:2.4:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.8.0:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.5:compile
[INFO] |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[INFO] +- joda-time:joda-time:jar:2.3:compile
[INFO] \- junit:junit:jar:4.8.2:test
