### ISSUE TITLE
Checking CheckBox on customfield

### ISSUE THREAD

**Issue by andrew-boutin** [rcarz/jira-client#71]
Hi, first of all thanks for creating this awesome tool!

In Jira I have a custom field that is of type Checkboxes with id = customfield_10023.  The only option is "Yes" which has an id of 10013.  I thought that doing what you did in the README.md file, for multi-select boxes, would work, but I can't seem to get it to.  Is it not supported or is there a different way to set check boxes?  Thank you very much.

    // Tried using the id
    symptom.update().field("customfield_10023", new ArrayList() {{
                       add(Field.valueById("10013"));
                  }})
                  .execute();

    // Also tried using the value
    symptom.update().field("customfield_10023", new ArrayList() {{
                       add("Yes");
                  }})
                  .execute();

Both ways I get the following error:

    Error during Jira Symptom creation: net.rcarz.jiraclient.JiraException: Failed to update issue TEST-1056
	net.rcarz.jiraclient.JiraException: Failed to update issue TEST-1056
		at net.rcarz.jiraclient.Issue$FluentUpdate.execute(Issue.java:191)
		at devopsdatamigrator.JiraHandle.createSymptom(JiraHandle.java:150)
		at devopsdatamigrator.DataMigrator.migrateIssues(DataMigrator.java:208)
		at devopsdatamigrator.DataMigrator.migrateObjects(DataMigrator.java:70)
		at devopsdatamigrator.DataMigrator.main(DataMigrator.java:252)
	Caused by: net.rcarz.jiraclient.RestException: 400 Bad Request: {"errorMessages":[],"errors":{"Customer Data Unavailable Flag":"expected Object"}}
		at net.rcarz.jiraclient.RestClient.request(RestClient.java:160)
		at net.rcarz.jiraclient.RestClient.request(RestClient.java:182)
		at net.rcarz.jiraclient.RestClient.request(RestClient.java:200)
		at net.rcarz.jiraclient.RestClient.put(RestClient.java:380)
		at net.rcarz.jiraclient.RestClient.put(RestClient.java:398)
		at net.rcarz.jiraclient.Issue$FluentUpdate.execute(Issue.java:189)

**Comment by rcarz** [comment]
Interesting. This might be similar to another issue someone e-mailed me about. Do you happen to know what the JSON is expected to look like? I haven't come across that field type before.

**Comment by andrew-boutin** [comment]
Does this help you at all?

    "customfield_10023":[{"value":"Yes","id":"10013"}]

I got this by viewing the issue's fields in a debugger after retrieving an issue from Jira - I manually set the checkbox using the Jira web interface so that's what it should "look like" when a checkbox is checked.

Thanks for the fast response on this!

**Comment by rcarz** [comment]
Yes that does help. I'll take a look soon.

**Comment by chaplinkyle** [comment]
What I have found so far:

I set up the same type of custom field in jira-client.atlassian.net. When you login check out https://jira-client.atlassian.net/rest/api/2/issue/JIR-1/editmeta. 

Field in question metadata: "customfield_10027":{"required":false,"schema":{"type":"array","items":"string","custom":"com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes","customId":10027}

Schema defines array of type string and that is what we're passing. I checked.

**Comment by andrew-boutin** [comment]
@chaplinkyle Did you attempt to set one of the checkboxes in the multicheckbox using jira-client?  Thanks for taking the time to look into this!

**Comment by andrew-boutin** [comment]
I'm not sure if the meta data I retrieved for my custom field helps in this issue or not:

customfield_10025 {"required":false,"schema": "type":"array","items":"string","custom":"com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes","customId":10025},"name":"Customer Data Loss Flag","hasDefaultValue":false,"operations":["add","set","remove"],"allowedValues":[{"self":"http://es-druedev-jira.lab.beer.town/jira/rest/api/2/customFieldOption/10014","value":"Yes","id":"10014"}]}

**Comment by andrew-boutin** [comment]
I have managed to set checkboxes, here is how:

    Issue symptom = jiraClient.getIssue("EM-559");
    
    JSONObject valueObject = new JSONObject(); // from import net.sf.json.JSONObject;
    valueObject.put("value", "Yes"); // Yes it the only option for this particular checkbox field
    ArrayList<Object> fields = new ArrayList<Object>();
    fields.add(valueObject);
			
    symptom.update().field("customfield_10023", fields).execute();

I'm not sure if it was designed to only work this way or if there is another way.  If not then I hope what I have found helps you fix the implementation.  At the least maybe now some comments can be made about how to set checkboxes with jira-client.  Thanks again for the awesome tool.

**Comment by rcarz** [comment]
That helped a lot actually. The problem is the metadata returned by JIRA lies about what the type actually is. An array of strings (as the metadata indicates) should be an array of strings, but it's really expecting an array of dictionaries.

Can you build jira-client from master and try this:

```
Issue symptom = jiraClient.getIssue("EM-559");
symptom.update().field("customfield_10023", new ArrayList<Object>() {{ add("Yes") }}).execute();
```

**Comment by stevegore** [comment]
Hi
I'm having this issue for all multi-select fields. I've tried your suggestion above to no avail. Any other suggestions? I've noticed there's an open feature request for this as well. https://github.com/rcarz/jira-client/issues/93

**Comment by andrew-boutin** [comment]
This should only work for check-boxes.  Multi-selects are a different story and expect a different format.  I haven't used the following, but this is from the documenation:

**MultiSelect**
"customfield_10008": [ {"value": "red" }, {"value": "blue" }, {"value": "green" }]

https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-create-issue

**Comment by andrew-boutin** [comment]
I just confirmed that this worked for me.  I created a custom field of type "Select List (multiple choices)" called "multiSelectTest" with custom field id "10101".  The available options were "one", "two", and "three".

    Issue problem = jiraClient.getIssue("EM-8648");

    JSONObject oneObject = new JSONObject(); // from import net.sf.json.JSONObject;
    oneObject.put("value", "one");
    JSONObject twoObject = new JSONObject();
    twoObject.put("value", "two");
			
    ArrayList<Object> fields = new ArrayList<Object>();
    fields.add(oneObject);
    fields.add(twoObject);
			
    problem.update().field("customfield_10101", fields).execute();

The String representation of 'fields' is "[{"value":"one"}, {"value":"two"}]".

Hope this helps!

**Comment by stevegore** [comment]
Thanks for this. I actually resolved the issue by making a change to the client. I'll try and create a pull request tomorrow.

**Comment by andrew-boutin** [comment]
I'm interested in knowing what wasn't working correctly with the client, I thought it was working correctly.

**Comment by stevegore** [comment]
https://github.com/rcarz/jira-client/pull/104

**Comment by stevegore** [comment]
Thanks for this. I actually resolved the issue by making a change to the client. I'll try and create a pull request tomorrow.
On 24 Jul 2015 12:29 am, Andrew Boutin <notifications@github.com> wrote:I just confirmed that this worked for me.  I created a custom field of type "Select List (multiple choices)" called "multiSelectTest" with custom field id "10101".  The available options were "one", "two", and "three".

Issue problem = jiraClient.getIssue("EM-8648");

JSONObject oneObject = new JSONObject(); // from import net.sf.json.JSONObject;
oneObject.put("value", "one");
JSONObject twoObject = new JSONObject();
twoObject.put("value", "two");

ArrayList<Object> fields = new ArrayList<Object>();
fields.add(oneObject);
fields.add(twoObject);

problem.update().field("customfield_10101", fields).execute();


The String representation of 'fields' is "[{"value":"one"}, {"value":"two"}]".

Hope this helps!

**Comment by stevenlordiam** [comment]
Can you update this merged code in Maven repo? Need this API so much. Thanks. @rcarz

**Comment by vzenzo** [comment]
Can somebody help with this? None of the options up there work for me, I constantly get 

400 400: {"errorMessages":[],"errors":{"Detected on Env":"expected Object","Country":"expected Object"}}

I've added them as objects 

        JSONObject envObject = new JSONObject();
        envObject.put("value", "UAT");
        envObject.put("id","10911");

        JSONObject countryObject = new JSONObject();
        countryObject.put("value", "RO");
        countryObject.put("id", "10900");

newIssue.field("customfield_11500", new ArrayList() {{add(countryObject);}})
                    .field("customfield_11503", new ArrayList() {{add(envObject);}})
                    .execute();
