### ISSUE TITLE
How to create bug in specific project

### ISSUE THREAD

**Issue by nikeshjauhari** [rcarz/jira-client#99]
I can create bug using following code

Issue newIssue = jira.createIssue("TEST", "Bug")
                .field(Field.SUMMARY, "Bat signal is broken")
                .field(Field.DESCRIPTION, "Commissioner Gordon reports the Bat signal is broken.")
                .field(Field.REPORTER, "batman")
                .field(Field.ASSIGNEE, "robin")
                .execute();

How do I make sure that above is created in a specific project ? where do I specify the project ?

Thanks,
Nikesh

**Comment by chaplinkyle** [comment]
In your example 'TEST' is the project key. Imagine if you have a project named 'Customer Support' and the key was 'CS' your issue creation could look like so:

Issue newIssue = jira.createIssue("CS", "Bug")
.field(Field.SUMMARY, "Bat signal is broken")
.field(Field.DESCRIPTION, "Commissioner Gordon reports the Bat signal is broken.")
.field(Field.REPORTER, "batman")
.field(Field.ASSIGNEE, "robin")
.execute();

**Comment by nikeshjauhari** [comment]
Thanks ... it works.
